### ISSUE TITLE
Error: Unable to locate package moonlight-embedded

### ISSUE THREAD

**Issue by vookhan** [moonlight-stream/moonlight-embedded#906]
I get this error after running sudo apt install moonlight-embedded .

This is after I have added the repository using curl .

How do I solve this error?

**Comment by cgutman** [comment]
What distro?

**Comment by alairjunior** [comment]
Raspberry Pi OS Lite - Trixie

**Comment by alairjunior** [comment]
3b+

**Comment by cgutman** [comment]
Yep, it's because we don't publish Trixie packages (yet). I did some work to get it building on Trixie.

Can you test these packages? https://nightly.link/cgutman/moonlight-embedded-packaging/actions/runs/19775497415

Use the `trixie-rpi` if you're running Raspberry Pi OS 32-bit or `trixie-rpi64` if you're using 64-bit.

**Comment by cgutman** [comment]
I tested this locally and released v2.7.1 with Trixie packages, so this is resolved.

**Comment by alairjunior** [comment]
Thanks @cgutman , sorry for not being able to complete the test. I don't have my setup available again until monday

**Comment by vookhan** [comment]
> I tested this locally and released v2.7.1 with Trixie packages, so this is resolved.

Sorry I'm not sure what testing locally means, do I need to put this zip on my SD card?

**Comment by cgutman** [comment]
There's nothing extra required now that v2.7.1 is released. You can simply follow the [installation steps](https://github.com/moonlight-stream/moonlight-embedded/wiki/Packages) now.

If you've already run `curl` command to install the repository, just run `sudo apt update` and then you can continue with the `sudo apt install moonlight-embedded` step from there. Be sure to also follow the steps in the "Additional Required Setup Steps" section too.

**Comment by vookhan** [comment]
Still getting `Error: Unable to locate package moonlight-embedded` on `sudo apt install moonlight-embedded` after `curl` .

Is v2.7.1 planned to be packaged for Debian? moonlight-embedded is not in official repositories:

```
vookhan@raspberrypi:~ $ apt-cache search moonlight
python3-miio - Python module for interfacing with Xiaomi appliances
moonlight-qt - NVIDIA GameStream client
moonlight-qt-dbgsym - debug symbols for moonlight-qt
```

```
 PRETTY_NAME="Debian GNU/Linux 13 (trixie)"
 NAME="Debian GNU/Linux"
 VERSION_ID="13"
 VERSION="13 (trixie)"
 VERSION_CODENAME=trixie
 DEBIAN_VERSION_FULL=13.2
 ID=debian
 HOME_URL="https://www.debian.org/"
 SUPPORT_URL="https://www.debian.org/support"
 BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by cgutman** [comment]
@vookhan are you using regular Debian or Raspberry Pi OS? Moonlight-embedded is only packaged for the latter (and even moonlight-qt probably won't work without the special FFmpeg patches that Raspberry Pi OS carries to handle their out-of-tree `rpivid` HEVC decoder).
